// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuluhsnkrhhotmpvuzey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1bHVoc25rcmhob3RtcHZ1emV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjA5MzksImV4cCI6MjA2Mjg5NjkzOX0.nGVmcOngiNGt_1nokvTizboQNt6qeaoZCGErT9PdUvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);